const productData = [
  {
    id: 1,
    name: " iphone xr ",
    image: "#",
    productType: "Iphone",
    price: " ₹ 35000 ",
    customer_Rating: 4.3,
    timeLeft: 27,
    totalSales: 7479,
  },
  {
    id: 2,
    name: " iphone 11 ",
    image: "#",
    productType: "Iphone",
    price: " ₹ 45000 ",
    customer_Rating: 4.1,
    timeLeft: 27,
    totalSales: 7479,
  },
  {
    id: 3,
    name: " iphone 12 mini ",
    image: "#",
    productType: "Iphone",
    price: " ₹ 40000 ",
    customer_Rating: 4.4,
    timeLeft: 27,
    totalSales: 7479,
  },
  {
    id: 4,
    name: " iphone 13 ",
    image: "#",
    productType: "Iphone",
    price: " ₹ 50000 ",
    customer_Rating: 4,
    timeLeft: 27,
    totalSales: 7479,
  },
];
